### PR TITLE
added models, tests, commands, and tembaclient

### PR DESCRIPTION
**Pull request by allandereal**
I have added a few functionalities, like creating models for contacts and messages.
creating commands to populate the database and creating tests.
please check the status, the next step will be to query the database for the info required. thats, contacts and messages.
And yes. i have also updated the requirements.pip file.

### CODE REVIEW

**Comment by xkmato** [comment]
Why are the checks failing?

**Comment by allandereal** [comment]
For the travis check, In the screen-shot below, i see no environmental variables set, could that be the problem?
qc reports travis failure

**Comment by xkmato** [comment]
Please ask for help where you're stuck. This is urgent

**Comment by xkmato** [comment]
The tests have to pass. You have to run `python manage.py test` and make sure that it passes before you can commit. If the tests do not pass, the build will fail. Also, make sure that all the pip requirements are reflected in the `requirements.pip`.
Click on one of those environments to see why the build failed

**Comment by allandereal** [comment]
The tests pass from manage.py

**Pull request closed without merging**
